// Generated by CoffeeScript 1.10.0
(function() {
  exports.retailer_list = ['Digikey', 'Mouser', 'RS', 'Newark', 'Farnell'];

  exports.field_list = ['partNumber', 'description'];

  exports.isComplete = function(lines) {
    var complete, f, i, j, k, len, len1, len2, line, r, ref, ref1;
    complete = true;
    for (i = 0, len = lines.length; i < len; i++) {
      line = lines[i];
      ref = exports.retailer_list;
      for (j = 0, len1 = ref.length; j < len1; j++) {
        r = ref[j];
        if (line.retailers[r] === '') {
          complete = false;
          break;
        }
      }
      if (!complete) {
        break;
      }
      ref1 = exports.field_list;
      for (k = 0, len2 = ref1.length; k < len2; k++) {
        f = ref1[k];
        if (line[f] === '') {
          complete = false;
          break;
        }
      }
    }
    return complete;
  };

  exports.hasSKUs = function(lines) {
    var hasSKUs, i, j, len, len1, line, r, ref;
    hasSKUs = false;
    for (i = 0, len = lines.length; i < len; i++) {
      line = lines[i];
      ref = exports.retailer_list;
      for (j = 0, len1 = ref.length; j < len1; j++) {
        r = ref[j];
        if (line.retailers[r] !== '') {
          hasSKUs = true;
          break;
        }
      }
      if (hasSKUs) {
        break;
      }
    }
    return hasSKUs;
  };

  exports.numberOfEmpty = function(lines) {
    var f, i, j, k, len, len1, len2, line, n, r, ref, ref1;
    n = 0;
    for (i = 0, len = lines.length; i < len; i++) {
      line = lines[i];
      ref = exports.field_list;
      for (j = 0, len1 = ref.length; j < len1; j++) {
        f = ref[j];
        if (line[f] === '') {
          n += 1;
        }
      }
      ref1 = exports.retailer_list;
      for (k = 0, len2 = ref1.length; k < len2; k++) {
        r = ref1[k];
        if (line.retailers[r] === '') {
          n += 1;
        }
      }
    }
    return n;
  };

}).call(this);

//# sourceMappingURL=line_data.js.map
