// Generated by CoffeeScript 1.10.0
(function() {
  var lineData, parser, writer;

  parser = require('./parser');

  writer = require('./writer');

  lineData = require('./line_data');

  exports.parseTSV = parser.parseTSV;

  exports.writeTSV = writer.writeTSV;

  exports.lineData = lineData;

}).call(this);

//# sourceMappingURL=main.js.map
