// Generated by CoffeeScript 1.10.0
(function() {
  var retailer_list;

  retailer_list = require('./line_data').retailer_list;

  exports.writeTSV = function(bom) {
    var i, j, k, len, len1, len2, line, r, ref, retailer;
    r = 'References\tQuantity\tPart Number\tDescription';
    for (i = 0, len = retailer_list.length; i < len; i++) {
      retailer = retailer_list[i];
      r += "\t" + retailer;
    }
    r += '\n';
    ref = bom.lines;
    for (j = 0, len1 = ref.length; j < len1; j++) {
      line = ref[j];
      r += "" + line.reference;
      r += "\t" + line.quantity;
      r += "\t" + line.partNumber;
      r += "\t" + line.description;
      for (k = 0, len2 = retailer_list.length; k < len2; k++) {
        retailer = retailer_list[k];
        if (line.retailers[retailer] != null) {
          r += "\t" + line.retailers[retailer];
        } else {
          r += '\t';
        }
      }
      r += '\n';
    }
    return r;
  };

}).call(this);

//# sourceMappingURL=writer.js.map
